AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  udacitywiki-sam

Resources:
  UdacityWikiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: udacitywiki/
      Handler: app.lambda_handler
      Runtime: python3.6
      MemorySize: 128
      Timeout: 15
      Events:
        ApiRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UdacityWikiApi:
    Description: "API Gateway endpoint URL for Prod stage for Udacity Wiki function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UdacityWikiFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt UdacityWikiFunction.Arn
  UdacityWikiFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UdacityWikiFunctionRole.Arn
